#!/usr/bin/ruby -w

require 'optparse'
require 'ostruct'


class GetTheOptions
	def self.parse(args)

		script_version = "0.01"
		options = OpenStruct.new
		options.device_list = []
		options.community = "public" #default to a common community string
		#options.warning = "0"
		#options.critical = "0"
		options.exit_status = "3"
		#options.maximum = "0"

		opts = OptionParser.new do |opts|
			opts.banner = "Usage: get_rtp_stats [options]"
			opts.on("-d", "--device", Array, "Input list of devices seperated by a comma") do |device|
				options.device_list = device
			end
			opts.on("-c", "--critical", "Specify crictal threshold") do |critical|
				options.critical = critical
			end
			opts.on("-w", "--warning", "Specify warning threshold") do |warning|
				options.warning = warning
			end
			opts.on("-m", "--maximum", "Specify max threshold") do |maximum|
				options.maximum = maximum
			end
			opts.on("-C", "--community", "Specify snmp community") do |community|
				options.maximum = community
			end
			opts.on("-v", "--version", "Prints Version of this script.") do
				puts "get_rtp_stats #{script_version}"
				exit
			end
			opts.on_tail("-h", "--help", "Show help message") do
				puts opts
				exit
			end
		end
		opts.parse!(args)
		options
	end
end

options = GetTheOptions.parse(ARGV)
puts options
