#!/usr/bin/ruby

require 'rubygems'
require 'optparse'
require 'ostruct'
require 'net/ping'
require 'pidfile'
require 'socket'
require 'snmp'

Dir["lib/*.rb"].each {|f| require_relative f}

pid_file = PidFile.new

check_for_libsmi

options = CommandLineOptions.parse(ARGV)
print_verbose("Script begin, verbose option enabled")

printer = Printer.new
graphite_server = GraphiteServer.new(address: options.graphite_server, port: options.graphite_server_port)

options.device_list.each do |item|
  device = Device.new(item,options.community)
  printer.add_command(device.graphite_status)
end

printer.print_to_screen
graphite_server.send_request(printer.request)
